// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2s3vWLFrvdZhYHMQX8zmelByruCEGCN0',
    appId: '1:783775866448:web:d8fb1f146a3bad79943b55',
    messagingSenderId: '783775866448',
    projectId: 'blackcarddenied',
    authDomain: 'blackcarddenied.firebaseapp.com',
    databaseURL: 'https://blackcarddenied-default-rtdb.firebaseio.com',
    storageBucket: 'blackcarddenied.firebasestorage.app',
    measurementId: 'G-JQWB20TSD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6fhbJigOz_jREsRJpcKan5qJ8E4EqeAQ',
    appId: '1:783775866448:android:f23301f57fea65d6943b55',
    messagingSenderId: '783775866448',
    projectId: 'blackcarddenied',
    databaseURL: 'https://blackcarddenied-default-rtdb.firebaseio.com',
    storageBucket: 'blackcarddenied.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJjP1GebHDuSIVlfCrIQlUb9tKDbLPp-w',
    appId: '1:783775866448:ios:bbff84d90fc7c9c1943b55',
    messagingSenderId: '783775866448',
    projectId: 'blackcarddenied',
    databaseURL: 'https://blackcarddenied-default-rtdb.firebaseio.com',
    storageBucket: 'blackcarddenied.firebasestorage.app',
    iosBundleId: 'com.ayoapps.blackCardDenied',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJjP1GebHDuSIVlfCrIQlUb9tKDbLPp-w',
    appId: '1:783775866448:ios:bbff84d90fc7c9c1943b55',
    messagingSenderId: '783775866448',
    projectId: 'blackcarddenied',
    databaseURL: 'https://blackcarddenied-default-rtdb.firebaseio.com',
    storageBucket: 'blackcarddenied.firebasestorage.app',
    iosBundleId: 'com.ayoapps.blackCardDenied',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2s3vWLFrvdZhYHMQX8zmelByruCEGCN0',
    appId: '1:783775866448:web:5a6dc6aee2ada634943b55',
    messagingSenderId: '783775866448',
    projectId: 'blackcarddenied',
    authDomain: 'blackcarddenied.firebaseapp.com',
    databaseURL: 'https://blackcarddenied-default-rtdb.firebaseio.com',
    storageBucket: 'blackcarddenied.firebasestorage.app',
    measurementId: 'G-4T4B7PBJKB',
  );
}
